// Prime Differences
// Copyright (c) 2025-2026 David Paul
// SPDX-License-Identifier: BSD-2-Clause
// This file is part of Prime Differences. See LICENSE for details.
#include "sys_info.hpp"

#include <bit>

// ---------------------------------------------------------------------------
// System Information
// ---------------------------------------------------------------------------

// Note: This code was generated by Gemini 3 Pro, and has only been tested on
// Linux

// ---------------------------------------------------------------------------
// Platform-Specific Headers
// ---------------------------------------------------------------------------

#if defined(_WIN32)
#include <windows.h>  // GetLogicalProcessorInformation

#include <memory>
#include <vector>
#elif defined(__APPLE__)
#include <sys/sysctl.h>  // sysctlbyname
#else                    // Linux / POSIX
#include <unistd.h>      // sysconf
#endif

// ---------------------------------------------------------------------------
// Cache Detection Logic
// ---------------------------------------------------------------------------

/// @brief Queries the OS for CPU cache characteristics.
///
/// Strategies:
/// - Windows: Iterates through the Logical Processor buffer.
/// - macOS: Strings based lookups via sysctl ("hw.l1dcachesize").
/// - Linux: Standard system configuration variables (via sysconf).
///
/// @return Struct containing L1, L2, L3 sizes in bytes (0 if undetected).
[[nodiscard]] cache_sizes get_cache_sizes() {
  cache_sizes sizes = {0, 0, 0};

#if defined(_WIN32)
  // --- Windows Implementation ---
  // Requires two calls: First to get buffer size, second to get data.
  DWORD buffer_size = 0;
  GetLogicalProcessorInformation(nullptr, &buffer_size);

  std::vector<SYSTEM_LOGICAL_PROCESSOR_INFORMATION> buffer(
      buffer_size / sizeof(SYSTEM_LOGICAL_PROCESSOR_INFORMATION));

  if (GetLogicalProcessorInformation(buffer.data(), &buffer_size)) {
    for (const auto& info : buffer) {
      if (info.Relationship == RelationCache) {
        // Note: This often returns info for just one Core. Since cores are
        // symmetrical, taking the first valid hit is usually sufficient.
        if (info.Cache.Level == 1)
          sizes.l1 = info.Cache.Size;
        else if (info.Cache.Level == 2)
          sizes.l2 = info.Cache.Size;
        else if (info.Cache.Level == 3)
          sizes.l3 = info.Cache.Size;
      }
    }
  }

#elif defined(__APPLE__)
  // --- macOS / BSD Implementation ---
  size_t len = sizeof(value_type);
  // 'hw.l1dcachesize' gets Data cache (Instructions cache is separate)
  sysctlbyname("hw.l1dcachesize", &sizes.l1, &len, nullptr, 0);
  sysctlbyname("hw.l2cachesize", &sizes.l2, &len, nullptr, 0);
  sysctlbyname("hw.l3cachesize", &sizes.l3, &len, nullptr, 0);

#else  // Linux / POSIX
  // --- Linux Implementation ---
  // constants like _SC_LEVEL1_DCACHE_SIZE are usually provided by glibc.
  long l1 = sysconf(_SC_LEVEL1_DCACHE_SIZE);
  long l2 = sysconf(_SC_LEVEL2_CACHE_SIZE);
  long l3 = sysconf(_SC_LEVEL3_CACHE_SIZE);

  if (l1 > 0) sizes.l1 = static_cast<value_type>(l1);
  if (l2 > 0) sizes.l2 = static_cast<value_type>(l2);
  if (l3 > 0) sizes.l3 = static_cast<value_type>(l3);
#endif

  // --- Fallbacks ---
  // If detection fails assume conservative "Safe" defaults for a modern CPU.
  if (sizes.l1 == 0) sizes.l1 = DEFAULT_L1_CACHE_SIZE;
  if (sizes.l2 == 0) sizes.l2 = DEFAULT_L2_CACHE_SIZE;
  if (sizes.l3 == 0) sizes.l3 = DEFAULT_L3_CACHE_SIZE;

  return sizes;
}

///  @brief Estimates the number of registers available for unrolling.
[[nodiscard]] value_type get_register_count_heuristic() {
#if defined(__aarch64__) || defined(_M_ARM64)
  // ARM64 has 31 General Purpose Registers (GPRs) + 32 SIMD registers.
  return 32;
#elif defined(__AVX512F__)
  // AVX-512 adds 32 vector registers (ZMM0-ZMM31).
  return 32;
#else
  // Standard x86-64 (SSE/AVX2) has only 16 General Purpose Registers and 16
  // vector registers. We reserve ~4 for pointers, leaving about 12 for free
  // usage.
  return 12;
#endif
}
